geoloc and searchbar fusioned
WildCodeSchool/toulouse-0919-js-p2-spot4sport pull request #8
Opened 2019-11-04 13:48 UTC by guigzzz31

2019-11-05 07:49 UTC, akopsykokwak requested changes

2019-11-05 07:49 UTC, akopsykokwak commented on src/components/MapTest.jsx
> +    const voilaZoom = isUserLocation ? this.state.zoom : this.props.zoomCity;
Need better name for variable

2019-11-05 07:49 UTC, akopsykokwak commented on src/components/MapTest.jsx
> +    const voilaCenter = isUserLocation ? position : this.props.cityCenter;
Need better name for variable

2019-11-05 11:04 UTC, guigzzz31 commented on src/components/MapTest.jsx
> +    const voilaZoom = isUserLocation ? this.state.zoom : this.props.zoomCity;
ok

2019-11-05 11:04 UTC, guigzzz31 commented on src/components/MapTest.jsx
> +    const voilaCenter = isUserLocation ? position : this.props.cityCenter;
ok

2019-11-06 09:29 UTC, akopsykokwak approved these changes

2019-11-06 09:48 UTC, Froyj approved these changes

2019-11-06 09:48 UTC, merged